name: jahrrr
version: 0.2.0+1
publish_to: "none"

description: CRM for designers to track clients, budgets, milestones, payments, deadlines, and analytics.

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  file_picker: ^8.0.6
  share_plus: ^9.0.0
  local_auth: ^2.2.0
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.5.7
  uuid: ^4.4.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  remove_alpha_ios: true
